//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Concurrent;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace App.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    [Table("Request")]
    public partial class Request
    {

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int RequestId { get; set; }

        [Required]
        [StringLength(100)]
        public string RequestDesc { get; set; }

        [ForeignKey("Status")]
        public byte StatusId { get; set; }

        public int StateId { get; set; }

        [ForeignKey("RequestDocType")]
        public byte RequestDocTypeId { get; set; }

        [ForeignKey("ReceiveDocType")]
        public byte ReceiveDocTypeId { get; set; }

        public int DeptId { get; set; }

        public int? DivId { get; set; }


        public virtual DocType RequestDocType { get; set; }
        public virtual DocType ReceiveDocType { get; set; }
        public virtual Status Status { get; set; }


        [ForeignKey("StateId")]
        public virtual StateView  State { get; set; }

        [ForeignKey("DivId")]
        public virtual DivisionView Division { get; set; }

        [ForeignKey("DeptId")]
        public virtual DepartmentView Department { get; set; }


    }
}
